require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
require 'fileutils'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'pushpull' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'npx',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    # Work around missing modulemaps under Pods/Headers/Public/* for some Swift pods.
    # We mirror each pod's generated *.modulemap + umbrella header from
    # Pods/Target Support Files/* into Pods/Headers/Public/<ModuleName>/.
    support_root = File.join(__dir__, 'Pods', 'Target Support Files')
    public_root = File.join(__dir__, 'Pods', 'Headers', 'Public')

    modules_to_mirror = %w[
      OpenIAP
      Stripe
      StripeApplePay
      StripeCore
      StripeFinancialConnections
      StripePaymentSheet
      StripePayments
      StripePaymentsUI
      StripeUICore
    ].freeze

    def safe_copy(src, dest)
      return unless File.exist?(src)

      if File.exist?(dest)
        begin
          return if File.realpath(src) == File.realpath(dest)
        rescue StandardError
          # If realpath fails (broken symlink, etc), fall through.
        end
        return
      end

      FileUtils.cp(src, dest)
    end

    Dir.glob(File.join(support_root, '*', '*.modulemap')).each do |modulemap_src|
      modulemap = File.read(modulemap_src)
      module_name = modulemap[/^\s*module\s+([A-Za-z0-9_]+)/, 1]
      umbrella_header = modulemap[/^\s*umbrella\s+header\s+\"([^\"]+)\"/, 1]
      next unless module_name && umbrella_header
      next unless modules_to_mirror.include?(module_name)

      support_dir = File.dirname(modulemap_src)
      umbrella_src = File.join(support_dir, umbrella_header)
      next unless File.exist?(umbrella_src)

      dest_dir = File.join(public_root, module_name)
      FileUtils.mkdir_p(dest_dir)
      safe_copy(modulemap_src, File.join(dest_dir, File.basename(modulemap_src)))
      safe_copy(umbrella_src, File.join(dest_dir, umbrella_header))
    end
  end
end
